app_demo/urls.py
from django.urls import path,re_path
from app_demo import views

app_name = 'app_demo'

urlpatterns = [
    path('main/', views.index_main, name='index_main'),
    path('context_menu/<str:pk>/', views.index_context_menu, name='index_context_menu'),
    path('courses/', views.index_courses, name='index_courses'),
    # Urls for Employee .....................................................................................
    path('employees/', views.index_employees, name='index_employees'),
    path('employee_create/', views.EmployeeCreateView.as_view(), name='index_employee_create'),
    path('employee_update/<str:pk>/', views.EmployeeUpdateView.as_view(), name='index_employee_update'),
    path('employee_delete/<str:pk>/', views.EmployeeDeleteView.as_view(), name='index_employee_delete'),
    # Urls for Sales ........................................................................................
    path('sales_tree/', views.index_sales_tree, name='index_sales_tree'),
    path('sales_list/', views.index_sales_list, name='index_sales_list'),
    path('sales_detail/<str:sales_id>/', views.index_sales_master_detail, name='index_sales_master_detail'),
    path('sales_update/<str:pk>/', views.SalesUpdateView.as_view(), name='index_sales_update'),
    path('sales_delete/<str:pk>/', views.SalesDeleteView.as_view(), name='index_sales_delete'),
    # Urls for SalesItem ....................................................................................
    path('sales_item_list/', views.index_sales_item_list, name='index_sales_item_list'),
    path('salesitem_create/<str:fk>/', views.SalesItemCreateView.as_view(), name='index_salesitem_create'),
    path('salesitem_update/<str:pk>/', views.SalesItemUpdateView.as_view(), name='index_salesitem_update'),
    path('salesitem_delete/<str:pk>/', views.SalesItemDeleteView.as_view(), name='index_salesitem_delete'),
    # Urls for Customer .....................................................................................
    path('customers/', views.index_customers, name='index_customers'),
    path('customer_create/', views.CustomerCreateView.as_view(), name='index_customer_create'),
    path('customer_update/<str:pk>/', views.CustomerUpdateView.as_view(), name='index_customer_update'),
    path('customer_delete/<str:pk>/', views.CustomerDeleteView.as_view(), name='index_customer_delete'),

    path('bar_chart_sales/', views.index_bar_chart_sales, name='index_bar_chart_sales'),
]

proj_demo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views

urlpatterns = [
    path('', include('app_demo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login',views.LoginView.as_view(), name='login'),
    path('accounts/logout',views.LogoutView.as_view(next_page='/main'), name='logout')
]

templates/standard/std_context_menu.html
<div class="menubar-wrapper">
    <div class="menubar">
        {% for dict_menu in list_dict_menu %}
            {% if dict_menu.children %}
                <li class="item link-submenu">
                    <div>
                        <i class="{{dict_menu.icon}}"></i>
                        <span>{{dict_menu.name}}</span>
                    </div>
                    <ul class="sub-menu">
                        {% for dict_sub_menu in dict_menu.children %}
                            <li class="item menu-click"
                                action-url="{% url 'app_demo:index_context_menu' pk='@pk@' %}"
                                action-title="{{dict_sub_menu.action_title}}"
                                action-index="{{dict_sub_menu.action_index}}" >
                                <div>
                                    <i class="{{dict_sub_menu.icon}}"></i>
                                    <span>{{dict_sub_menu.name}}</span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% else %}
                <li class="item menu-click"
                    action-url="{% url 'app_demo:index_context_menu' pk='@pk@' %}"
                    action-title="{{dict_menu.action_title}}"
                    action-index="{{dict_menu.action_index}}" >
                    <div>
                        <i class="{{dict_menu.icon}}"></i>
                        <span>{{dict_menu.name}}</span>
                    </div>
                </li>
            {% endif %}
        {% endfor %}
    </div>
</div>

templates/standard/std_tree_node.html
{% for dict_node in list_dict_node %}
     {% if dict_node.children %}
         <li>
             <div class="row-select node-select tree-node-parent">
             <i class="fas fa-angle-right rotate"></i>
             <span class="node-value" style="width:100%">
                 <i class="{{dict_node.icon}} ic-w mx-1"></i>{{dict_node.name}}</span>
             </div>
             <ul class="nested" style="background:alicebluealiceblue;color:black">
                 {% with list_dict_node=dict_node.children template_name="standard/std_tree_node.html" %}
                   {% include template_name %}
                {% endwith %}
             </ul>
         </li>
     {% else %}
        <li>
            <div class="row-select node-select">
                <span class="node-value" style="width:100%"><i class="{{dict_node.icon}} ic-w mr-1"></i>{{dict_node.name}}</span>
            </div>
        </li>
     {% endif %}
{% endfor %}