app_demo/urls.py
from django.urls import path,re_path
from app_demo import views

app_name = 'app_demo'

urlpatterns = [
    path('main/', views.index_main, name='index_main'),
    path('context_menu/<str:pk>/', views.index_context_menu, name='index_context_menu'),
    path('courses/', views.index_courses, name='index_courses'),
    # Urls for Employee .....................................................................................
    path('employees/', views.index_employees, name='index_employees'),
    path('employee_create/', views.EmployeeCreateView.as_view(), name='index_employee_create'),
    path('employee_update/<str:pk>/', views.EmployeeUpdateView.as_view(), name='index_employee_update'),
    path('employee_delete/<str:pk>/', views.EmployeeDeleteView.as_view(), name='index_employee_delete'),
    # Urls for Sales ........................................................................................
    path('sales_tree/', views.index_sales_tree, name='index_sales_tree'),
    path('sales_list/', views.index_sales_list, name='index_sales_list'),
    path('sales_detail/<str:sales_id>/', views.index_sales_master_detail, name='index_sales_master_detail'),
    path('sales_update/<str:pk>/', views.SalesUpdateView.as_view(), name='index_sales_update'),
    path('sales_delete/<str:pk>/', views.SalesDeleteView.as_view(), name='index_sales_delete'),
    # Urls for SalesItem ....................................................................................
    path('sales_item_list/', views.index_sales_item_list, name='index_sales_item_list'),
    path('salesitem_create/<str:fk>/', views.SalesItemCreateView.as_view(), name='index_salesitem_create'),
    path('salesitem_update/<str:pk>/', views.SalesItemUpdateView.as_view(), name='index_salesitem_update'),
    path('salesitem_delete/<str:pk>/', views.SalesItemDeleteView.as_view(), name='index_salesitem_delete'),
    # Urls for Customer .....................................................................................
    path('customers/', views.index_customers, name='index_customers'),
    path('customer_create/', views.CustomerCreateView.as_view(), name='index_customer_create'),
    path('customer_update/<str:pk>/', views.CustomerUpdateView.as_view(), name='index_customer_update'),
    path('customer_delete/<str:pk>/', views.CustomerDeleteView.as_view(), name='index_customer_delete'),

    path('bar_chart_sales/', views.index_bar_chart_sales, name='index_bar_chart_sales'),
]

proj_demo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views

urlpatterns = [
    path('', include('app_demo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login',views.LoginView.as_view(), name='login'),
    path('accounts/logout',views.LogoutView.as_view(next_page='/main'), name='logout')
]

app_demo/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    id = models.CharField(max_length=3,primary_key=True,db_column='dept_id')
    name = models.CharField(max_length=50,db_column='dname',unique=True)
    location = models.CharField(max_length=50,db_column='loc')

    class Meta:
        db_table = 'dept'

    def __str__(self):
        return self.name

class Employee(models.Model):
    id = models.CharField(max_length=4,primary_key=True,db_column='emp_id')
    name = models.CharField(max_length=255,db_column='ename',unique=True)
    designation = models.CharField(max_length=40,db_column='desig')
    joining_date = models.DateField(db_column='doj')
    basic = models.DecimalField(max_digits=12,decimal_places=2,db_column='basic')
    allowence = models.DecimalField(max_digits=12,decimal_places=2,db_column='allowence')
    address = models.CharField(max_length=500,db_column='add_line')
    city = models.CharField(max_length=100,db_column='city')
    contact_no = models.CharField(max_length=50,db_column='contact_no')
    department = models.ForeignKey(Department,on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'emp'

    def __str__(self):
        return self.name

class Customer(models.Model):
    id = models.CharField(max_length=4,primary_key=True,db_column='cust_id')
    name = models.CharField(max_length=100,db_column='cust_name',unique=True)
    credit_limit = models.DecimalField(max_digits=2,decimal_places=0,db_column='credit_limit')
    address = models.CharField(max_length=255,db_column='address')
    landmark = models.CharField(max_length=255, db_column='landmark')
    city = models.CharField(max_length=50, db_column='city')
    state = models.CharField(max_length=50, db_column='state')

    class Meta:
        db_table = 'customer'

    def __str__(self):
        return self.name

class Product(models.Model):
    id = models.CharField(max_length=4,primary_key=True,db_column='product_id')
    name = models.CharField(max_length=100,db_column='product_name',unique=True)
    manufacturer = models.CharField(max_length=100,db_column='manufacturer')
    cost_rate = models.DecimalField(max_digits=12,decimal_places=2,db_column='cost_rate')

    class Meta:
        db_table = 'product'

    def __str__(self):
        return self.name


class Sales(models.Model):
    id = models.AutoField(primary_key=True,db_column='sales_id')
    date = models.DateField(db_column='sales_date')
    customer = models.ForeignKey(Customer,on_delete=models.DO_NOTHING)
    gross_amount = models.DecimalField(max_digits=12,decimal_places=2,db_column='gross_amt')
    disc_rate = models.DecimalField(max_digits=5,decimal_places=2,db_column='disc_rate')
    disc_amount = models.DecimalField(max_digits=12, decimal_places=2, db_column='disc_amt')
    net_amount = models.DecimalField(max_digits=12, decimal_places=2, db_column='net_amt')

    def __str__(self):
        return 'Invoice No - ' + str(self.id)

class SalesItem(models.Model):
    id = models.AutoField(primary_key=True, db_column='sales_item_id')
    sales = models.ForeignKey(Sales,on_delete=models.DO_NOTHING)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    rate = models.DecimalField(max_digits=12, decimal_places=2, db_column='rate')
    qty = models.DecimalField(max_digits=5, decimal_places=0, db_column='qty')
    amount = models.DecimalField(max_digits=12, decimal_places=2, db_column='disc_amt')

app_demo/forms.py
from django import forms
from app_demo.models import Employee,Sales,SalesItem,Customer
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit,Field

class DateInput(forms.DateInput):
    input_type = 'date'

class EmployeeForm(forms.ModelForm):
    desig_choices = (('Manager', 'Manager'),
                     ('Officer', 'Officer'),
                     ('Clerk', 'Clerk'),
                     ('Engineer', 'Engineer'),
                     ('Worker', 'Worker'),
                     ('Salesman', 'Salesman')
                     )

    joining_date = forms.DateField(localize=True, widget=DateInput)
    designation = forms.ChoiceField(choices=desig_choices)

    class Meta():
        model = Employee
        fields = '__all__'

class SalesForm(forms.ModelForm):
    class Meta():
        model = Sales
        fields = '__all__'

    date = forms.DateField(localize=True, widget=DateInput)

class SalesItemForm(forms.ModelForm):

    class Meta():
        model = SalesItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SalesItemForm, self).__init__(*args, **kwargs)
        self.fields['sales'] .disabled = True

class CustomerForm(forms.ModelForm):
    class Meta():
        model = Customer
        fields = '__all__'

app_demo/views.py
from django.shortcuts import render
from app_demo.models import Employee,Sales,SalesItem,Customer
from django.db.models import Max,Min,Sum
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from app_demo.forms import EmployeeForm,SalesForm,SalesItemForm,CustomerForm
from django.urls import reverse,reverse_lazy
from django.contrib import messages
import app_demo.data_utils as data_utils
import app_demo.data.context_menu as ctxt_menu
import plotly.express as px
from plotly.offline import plot
import pandas as pd

dict_period = {}

# Dumy url for context menu
def index_context_menu(request):
  return render(request, 'app_demo/main.html')

# All Index Base View Here ......................................................................
def index_main(request):
  messages.add_message(request, messages.INFO, "Hello world.")
  return render(request, 'app_demo/main.html')

def index_courses(request):
    emps = Employee.objects.all()
    dict_context = {}
    dict_context['employee_list'] = emps
    return render(request,'app_demo/cards.html',context=dict_context)

# Class Base View of Employee ...................................................................
def index_employees(request):
    dict_context = {}
    dict_context['employee_list'] = Employee.objects.all()
    dict_context['list_dict_menu'] = ctxt_menu.ContextMenuProvider.get_instance()._get_context_menu('employee_right_click')
    return render(request, 'app_demo/list_employee.html', context=dict_context)

class EmployeeListView(ListView):
    model = Employee
    template_name = 'app_demo/list_employee.html'
    # employee_list is the variable generated by ListVIew model

class EmployeeCreateView(CreateView):
    form_class = EmployeeForm
    model = Employee
    template_name = 'app_demo/detail_employee.html'
    success_url = reverse_lazy('app_demo:index_employees')

class EmployeeUpdateView(UpdateView):
    form_class = EmployeeForm
    model = Employee
    template_name = 'app_demo/detail_employee.html'
    success_url = reverse_lazy('app_demo:index_employees')

    def form_valid(self, form):
        print('Employee Saved')
        return super().form_valid(form)

class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = 'app_demo/delete_any.html'
    success_url = reverse_lazy('app_demo:index_employees')

# Class/Index Base View of Sales and ........................................................................

class SalesListView(ListView):
    model = Sales
    template_name = 'app_demo/tree_list_sales.html'
    # sales_list is the variable generated by ListVIew model

def index_sales_tree(request):
    dict_range = Sales.objects.aggregate(dt_min_sales=Min("date"), dt_max_sales=Max("date"))
    print(dict_range)
    dt_min = dict_range['dt_min_sales']
    dt_max = dict_range['dt_max_sales']
    global dict_period
    dict_period, list_dict_tree = data_utils.get_period_tree(dt_min, dt_max)
    sales = Sales.objects.all()

    dict_context = {}
    dict_context['tree_nodes_sales'] = list_dict_tree
    dict_context['dict_period'] = dict_period
    dict_context['sales_list'] = sales
    return render(request, 'app_demo/tree_list_sales.html', context=dict_context)

def index_sales_list(request):
    node_id = request.GET['row_id']
    global dict_period
    from_date = dict_period[node_id]['from_date']
    to_date = dict_period[node_id]['to_date']
    sales = Sales.objects.filter(date__gte=from_date, date__lte=to_date)

    dict_sub_menu1 = {'name': 'CSV File','icon':'fa fa-file-text-o'}
    dict_sub_menu2 = {'name': 'Excel File','icon':'fa fa-file-excel-o'}
    list_dict_submenu = [dict_sub_menu1,dict_sub_menu2]

    dict_menu1 = {'name': 'Export','icon':'fa fa-share','children':list_dict_submenu}
    dict_menu2 = {'name': 'Import','icon':'fa fa-reply'}
    list_dict_menu = [dict_menu1,dict_menu2]
    print(dict_menu1['children'])

    dict_context = {}
    dict_context['sales_list'] = sales
    dict_context['list_dict_menu'] = ctxt_menu.ContextMenuProvider.get_instance()._get_context_menu('sales_right_click')
    return render(request, 'app_demo/list_sales.html', context=dict_context)

class SalesUpdateView(UpdateView):
    form_class = SalesForm
    model = Sales
    template_name = 'app_demo/detail_sales.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('app_demo:index_sales_master_detail', args=(self.object.id,))

class SalesDeleteView(DeleteView):
    model = Sales
    template_name = 'app_demo/delete_any.html'
    success_url = reverse_lazy('app_demo:index_sales')

# Class/Index Base View of SalesItem.........................................................................

def index_sales_master_detail(request,sales_id):
    obj_sales = Sales.objects.get(id=sales_id)
    list_sales_item = SalesItem.objects.filter(sales=obj_sales)
    return render(request, 'app_demo/master_detail_sales.html', context={'sales':obj_sales,'sales_items':list_sales_item})

def index_sales_item_list(request):
    sales_id = request.GET['row_id']
    obj_sales = Sales.objects.get(id=sales_id)
    list_sales_item = SalesItem.objects.filter(sales=obj_sales)
    print(list_sales_item)
    print('-----------------')
    dict_context = {}
    dict_context['sales_item_list'] = list_sales_item
    return render(request, 'app_demo/list_sales_item.html',context=dict_context)

class SalesItemCreateView(CreateView):
    form_class = SalesItemForm
    model = SalesItem
    template_name = 'app_demo/detail_sales_item.html'

    def get_initial(self, **kwargs):
        obj_sales = Sales.objects.get(id=self.kwargs.get('fk'))
        return {'qty': 1,'sales':obj_sales}

    def get_success_url(self, **kwargs):
        obj_sales = Sales.objects.get(id=self.kwargs.get('fk'))
        update_salee(obj_sales)
        return reverse_lazy('app_demo:index_sales_master_detail', args=(self.object.sales.id,))

class SalesItemUpdateView(UpdateView):
    form_class = SalesItemForm
    model = SalesItem
    template_name = 'app_demo/detail_sales_item.html'

    def get_success_url(self, **kwargs):
        update_salee(self.object.sales)
        return reverse_lazy('app_demo:index_sales_master_detail', args=(self.object.sales.id,))

class SalesItemDeleteView(DeleteView):
    model = SalesItem
    template_name = 'app_demo/delete_any.html'

    def get_success_url(self, **kwargs):
        update_salee(self.object.sales,self.object)
        return reverse_lazy('app_demo:index_sales_master_detail', args=(self.object.sales.id,))

def update_salee(sales,deleteditem=None):
    list_sales_item = SalesItem.objects.filter(sales=sales)
    if deleteditem != None:
        list_sales_item = [si for si in list_sales_item if si.id != deleteditem.id]
    gross_amt = sum([si.amount for si in list_sales_item])
    dist_amt = (gross_amt * sales.disc_rate)/100
    sales.gross_amount = gross_amt
    sales.disc_amount = dist_amt
    sales.net_amount = gross_amt - dist_amt
    sales.save()
    pass

# Class and Index Base View of Customer ...................................................................
class CustomerListView(ListView):
    model = Customer
    template_name = 'app_demo/list_customer.html'
    # customer_list is the variable generated by ListVIew model

def index_customers(request):
    # Chart for customer wise total sales
    qs_sum_sales_by_cust = Sales.objects.values('customer').annotate(total_sales=Sum('net_amount')).order_by('customer')
    df_sum_sales_by_cust = pd.DataFrame.from_records(qs_sum_sales_by_cust)
    df_sum_sales_by_cust = df_sum_sales_by_cust.rename(columns={'total_sales': 'Total Sales', 'customer': 'Customer ID'})
    fig = px.bar(df_sum_sales_by_cust, x='Customer ID', y="Total Sales", title='Customer wise Total Sales')
    fig.update_layout(autosize=False,width=840,height=330,margin=dict( l=10,r=10, b=10, t=30,pad=4),)
    fig.update_traces(marker_color='cadetblue')
    fig.update_layout(paper_bgcolor="aliceblue")
    chart_bar_sales = plot({'data': fig}, output_type='div')

    dict_context = {}
    dict_context['customer_list'] = Customer.objects.all()
    dict_context['chart_bar_sales'] = chart_bar_sales
    return render(request, 'app_demo/list_customer.html', context=dict_context)

class CustomerCreateView(CreateView):
    form_class = CustomerForm
    model = Customer
    template_name = 'app_demo/detail_customer.html'
    success_url = reverse_lazy('app_demo:index_customers')

class CustomerUpdateView(UpdateView):
    form_class = CustomerForm
    model = Customer
    template_name = 'app_demo/detail_customer.html'
    success_url = reverse_lazy('app_demo:index_customers')

    def form_valid(self, form):
        print('Customr Saved')
        return super().form_valid(form)

    def form_invalid(self, form):
        print('Customr not saved')
        return super().form_invalid(form)

class CustomerDeleteView(DeleteView):
    model = Customer
    template_name = 'app_demo/delete_any.html'
    success_url = reverse_lazy('app_demo:index_customers')

def index_bar_chart_sales(request):
    cust_id = request.GET['row_id']
    obj_cust = Customer.objects.get(id=cust_id)
    qs_sales = Sales.objects.filter(customer=obj_cust).order_by('date')
    df_sales = pd.DataFrame.from_records(qs_sales.values())
    df_sales = df_sales.rename(columns={'net_amount': 'Amount', 'date': 'Sales Date'})
    fig = px.line(df_sales, x='Sales Date', y="Amount",markers=True,title='Sales trend for customer : '+obj_cust.name)
    fig.update_layout(autosize=False,width=840,height=330,margin=dict( l=10,r=10, b=10, t=30,pad=4),)
    fig.update_traces(line_color='cadetblue')
    fig.update_layout(paper_bgcolor="aliceblue")
    chart_Line_sales = plot({'data': fig}, output_type='div')
    return render(request, 'app_demo/charts/bar_chart_sales.html', context={'chart_Line_sales':chart_Line_sales})

templates/app_demo/cards.html
{% extends 'app_demo/main.html' %}
{% load static %}
{% block content %}
<div>
<div class="row">
  <div class="col-sm-4">
    <div class="card">
        <div class="card-header">Python Basic</div>
        <div class="card-body">
            <h6 class="card-title">Special title treatment</h6>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card">
        <div class="card-header">Python Advanced</div>
        <div class="card-body">
            <h6 class="card-title">Special title treatment</h6>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.
                Course Duration
                Course Fees
            </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card">
        <div class="card-header">Django Web Development</div>
        <div class="card-body">
            <h6 class="card-title">Special title treatment</h6>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
  </div>

</div>
    </div>
{% endblock %}

templates/app_demo/delete_any.html
<div class="jumbotron">
    <div class="confirm-delete">
        <h6>Confirm to delete this Entry!!</h6>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">Cancel</button>
        <form method="post" action="{{request.path}}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" >Delete</button>
        </form>
    </div>
</div>

templates/app_demo/list_customer.html
{% extends 'app_demo/main.html' %}
{% load static %}
{% block content %}
  <div class="panel-container-h" style="height:100%">
    <div style="width:100%;height:50%" id="customer_view" class="panel-top table-wrap">
        {% with customer_list=customer_list template_name="app_demo/tables/table_customer.html" %}
          {% include template_name %}
        {% endwith %}
    </div>
    <div class="splitter-h"><div class="splitter-h-line"></div></div>
    <div class="panel-bottom panel-container-v" style="width:100%;height:50%" >
      <div id="bar_chart_view" class="panel-left" style="width:50%;height:100%">
        {{chart_bar_sales|safe}}
      </div>
      <div class="splitter-v"><div class="splitter-v-line"></div></div>
      <div id="line_chart_view" class="panel-right" style="width:50%;height:100%">
     </div>
    </div>
  </div>
  {% if list_dict_menu %}
    {% with list_dict_menu=list_dict_menu template_name="standard/std_context_menu.html" %}
      {% include template_name %}
    {% endwith %}
  {% endif %}
  <script src="{% static './js/standard.js' %}"></script>
  <script>
    configSelectionEvent("tbl_customer");
    configOnSelectionView('tbl_customer',"{% url 'app_demo:index_bar_chart_sales' %}","line_chart_view");
  </script>
{% endblock %}

templates/app_demo/list_employee.html
{% extends 'app_demo/main.html' %}
{% load static %}
{% block content %}
  <div style="width:100%;height: 100%">
    <div class="row" >
      <div id="div_employee_action" class="col-sm-12 col-md-6 input">
         <a class="show-standard-popup btn"
             data-title="Add Department"
             data-popup-url="{% url 'app_demo:index_employee_create' %}">Add Employee</a>
      </div>
      <div id="div_employee_filter" class="col-sm-12 col-md-3"></div>
      <div id="div_employee_pagination" class="col-sm-12 col-md-3"></div>
    </div>
    {% if employee_list %}
    <div style="width:100%;height:95%" class="table-wrap">
      <table id="tbl_employee" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
        <thead class="table-header-color">
        <tr>
          <th class="th-sm">Action</th>
          <th class="th-sm">Id</th>
          <th class="th-sm">Name</th>
          <th class="th-sm">Designation</th>
          <th class="th-sm">Department</th>
          <th class="th-sm">Joining Date</th>
          <th class="th-sm">Basic</th>
          <th class="th-sm">Allowence</th>
          <th class="th-sm">City</th>
        </tr>
        </thead>
        <tbody>
          {% for emp in employee_list %}
            <tr class="row-select">
              <td>
                <a class="show-standard-popup"
                         data-title="Edit Employee"
                         data-popup-url="{% url 'app_demo:index_employee_update' pk=emp.id %}">
                  <i class="far fa-edit" style="color: red;"></i>
                </a>
                <a class="show-standard-popup"
                         data-title="Delete Department"
                         data-popup-url="{% url 'app_demo:index_employee_delete' pk=emp.id %}">
                  <img src="{% static 'icons/delete.png' %}"/>
                </a>
              </td>
              <td class="row_id">{{emp.id}}</td>
              <td>{{emp.name}}</td>
              <td>{{emp.designation}}</td>
              <td>{{emp.department.name}}</td>
              <td>{{emp.joining_date}}</td>
              <td>{{emp.basic}}</td>
              <td>{{emp.allowence}}</td>
              <td>{{emp.city}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% else %}
    <h3>No Employee Informations</h3>
  {% endif %}
  {% if list_dict_menu %}
    {% with list_dict_menu=list_dict_menu template_name="standard/std_context_menu.html" %}
      {% include template_name %}
    {% endwith %}
  {% endif %}
  <script src="{% static './js/standard.js' %}"></script>
  <script>
    configSelectionEventWithContextMenu("tbl_employee");
  </script>
{% endblock %}

templates/app_demo/list_sales.html
{% load static %}
{% block content %}
  {% if list_dict_menu %}
    {% with list_dict_menu=list_dict_menu template_name="standard/std_context_menu.html" %}
      {% include template_name %}
    {% endwith %}
  {% else %}
    <h1>Not found </h1>
  {% endif %}
  {% with sales_list1=sales_list template_name="app_demo/tables/table_sales.html" %}
    {% include template_name %}
  {% endwith %}
  <script src="{% static './js/standard.js' %}"></script>
  <script>


    configSelectionEventWithContextMenu("dtBasic1");
    configOnSelectionView('dtBasic1',"{% url 'app_demo:index_sales_item_list' %}","sales_item_view");
  </script>
{% endblock %}

templates/app_demo/master_detail_sales.html
{% extends 'app_demo/main.html' %}
{% load static %}
{% block content %}
<div class="panel-container-v" style="width:100%;height:100%" xmlns="http://www.w3.org/1999/html">
    <div class="panel-left" style="width:30%;height: 100%">
        <div class="div_right">
            <a class="btn show-standard-popup"
                       data-title="Edit Sales"
                       data-popup-url="{% url 'app_demo:index_sales_update' pk=sales.id %}">Edit
            </a>
        </div>
        <div>
             <table id="dtBasic" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th class="th-sm th_title" width="30%">Sales Details</th>
                        <th class="th-sm th_title" ></th>
                    </tr>
                </thead>
                <tbody>
                    <tr><td>Invoice No.</td><td>{{sales.id}}</td></tr>
                    <tr><td>Invoice Date</td><td>{{sales.date}}</td></tr>
                    <tr><td>Gross Amount</td><td>{{sales.gross_amount}}</td></tr>
                    <tr><td>Discount Rate</td><td>{{sales.disc_rate}}</td></tr>
                    <tr><td>Discount</td><td>{{sales.disc_amount}}</td></tr>
                    <tr><td>Invoice Amount</td><td>{{sales.net_amount}}</td></tr>
                </tbody>
             </table>
            </br>
            <table id="dtBasic" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
                <thead >
                    <tr>
                        <th class="th-sm th_title" width="30%">Customer Details</th>
                        <th class="th-sm th_title"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr><td>Name</td><td>{{sales.customer.name}}</td></tr>
                    <tr><td>Address</td><td>{{sales.customer.address}}</td></tr>
                    <tr><td>Landmark</td><td>{{sales.customer.landmark}}</td></tr>
                    <tr><td>City</td><td>{{sales.customer.city}}</td></tr>
                    <tr><td>State</td><td>{{sales.customer.state}}</td></tr>
                </tbody>
             </table>
        </div>
    </div>
    <div class="splitter-v"><div class="splitter-v-line"></div></div>
    <div class="panel-right" style="width: 70%;height:100%">
        <div>
            <a id="#add_button" class="show-standard-popup"
                       data-title="Add Sales Item"
                       data-popup-url="{% url 'app_demo:index_salesitem_create' fk=sales.id %}">
                <i class="fa fa-plus-circle" style="color: #265481;font-size: 1.5rem"></i>
              </a>
        </div>
        <div>
            <table id="dtHorizontalVerticalExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
                <thead class="table-header-color">
                    <tr>
                        <th></th>
                        <th class="th-sm">Sr.</th>
                        <th class="th-sm">Product</th>
                        <th class="th-sm">Cost</th>
                        <th class="th-sm">Manufacturer</th>
                        <th class="th-sm">Rate</th>
                        <th class="th-sm">Quantity</th>
                        <th class="th-sm">Amount</th>
                        <th class="th-sm">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sales_item in sales_items %}
                        <tr>
                            <td></td>
                            <td>{{sales_item.id}}</td>
                            <td>{{sales_item.product.name}}</td>
                            <td>{{sales_item.product.cost_rate}}</td>
                            <td>{{sales_item.product.manufacturer}}</td>
                            <td>{{sales_item.rate}}</td>
                            <td>{{sales_item.qty}}</td>
                            <td>{{sales_item.amount}}</td>
                            <td>
                              <a class="show-standard-popup"
                                       data-title="Edit Sales Item"
                                       data-popup-url="{% url 'app_demo:index_salesitem_update' pk=sales_item.id %}">
                                <i class="far fa-edit" style="color: red;"></i>
                              </a>
                              <a class="show-standard-popup"
                                       data-title="Delete Sales Item"
                                       data-popup-url="{% url 'app_demo:index_salesitem_delete' pk=sales_item.id %}">
                                <img src="{% static 'icons/delete.png' %}"/>
                              </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
         </table>
        </div>
    </div>
</div>
{% endblock %}